// node --test tests/ — the lessons manifest (app/data/grammar/lessons/index.json,
// generated by pipeline/build_lessons_index.py) and the loader over it: a
// skill the manifest does not list is the "lesson coming" placeholder with
// no request; the manifest on disk matches the lesson files that exist and
// every id is a skill in skills.json.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { manifestIds, createLessonLoader, normaliseLesson, indexSkills } from '../app/js/grammar/lessons.js';

const dataDir = new URL('../app/data/grammar/', import.meta.url);
const read = (name) => JSON.parse(readFileSync(new URL(name, dataDir), 'utf8'));

test('manifestIds: a list of ids (or file names), anything else → null', () => {
  assert.deepEqual([...manifestIds({ version: 1, lessons: ['a', 'b.json', '', 3] })], ['a', 'b']);
  assert.deepEqual([...manifestIds(['x'])], ['x']);
  assert.equal(manifestIds({}), null);
  assert.equal(manifestIds(null), null);
});

test('loader: listed lessons are fetched once; unlisted ones are null without a request; no manifest → ask, a miss is null', async () => {
  const calls = [];
  const files = { 'lessons/index.json': { lessons: ['dative-indirect-object'] }, 'lessons/dative-indirect-object.json': { skill: 'dative-indirect-object', core: [{ type: 'p', text: 'x' }, null, { text: 'no type' }], more: 'nope' } };
  const fetchJson = async (name) => { calls.push(name); if (!(name in files)) throw new Error(`${name}: 404`); return files[name]; };
  const loader = createLessonLoader({ fetchJson });
  const l = await loader.loadLesson('dative-indirect-object');
  assert.deepEqual(l, { skill: 'dative-indirect-object', core: [{ type: 'p', text: 'x' }], more: [], sources: [], sample: false });
  assert.equal(await loader.loadLesson('dative-indirect-object'), l, 'cached');
  assert.equal(await loader.loadLesson('genitive-of'), null);
  assert.equal(await loader.hasLesson('genitive-of'), false);
  assert.equal(await loader.hasLesson('dative-indirect-object'), true);
  assert.deepEqual(calls, ['lessons/index.json', 'lessons/dative-indirect-object.json'], 'the manifest once, the listed lesson once, nothing for the unlisted skill');
  // No manifest (an old deploy, offline before it was cached): every lesson is asked for; a 404 is the placeholder.
  const calls2 = [];
  const loader2 = createLessonLoader({ fetchJson: async (name) => { calls2.push(name); if (name === 'lessons/x.json') return { skill: 'x' }; throw new Error('404'); } });
  assert.equal((await loader2.loadLesson('x')).skill, 'x');
  assert.equal(await loader2.loadLesson('y'), null);
  assert.deepEqual(calls2, ['lessons/index.json', 'lessons/x.json', 'lessons/y.json']);
  assert.equal(normaliseLesson({ skill: 's' }).core.length, 0);
});

test('index.json on disk lists exactly the lesson files present, each a skill of skills.json (run python pipeline/build_lessons_index.py)', () => {
  const manifest = read('lessons/index.json');
  const onDisk = readdirSync(new URL('lessons/', dataDir)).filter((f) => f.endsWith('.json') && f !== 'index.json' && !f.endsWith('.sample.json')).map((f) => f.replace(/\.json$/, '')).sort();
  assert.deepEqual([...manifest.lessons].sort(), onDisk, 'the manifest is stale: python pipeline/build_lessons_index.py');
  const index = indexSkills(read('skills.json'));
  assert.equal(index.skills.size, 87);
  for (const id of manifest.lessons) {
    assert.ok(index.skills.has(id), `${id} is not a skill`);
    assert.equal(read(`lessons/${id}.json`).skill, id, `${id}.json names another skill`);
  }
  assert.ok(!onDisk.some((f) => f.endsWith('.sample')), 'no sample fixtures ship');
});
