"""Validator for the chapter 22-27 teaching sentences and lesson `teach` blocks.

Contract: docs/GRAMMAR-CONTRACT.md, "# Teaching rebuild (2026-09-09)", sections 1 and 2.

Covers the eight skills written for chapters 22-27:
  perfect-deponent, future-participle, future-infinitive, pluperfect,
  ablative-comparison, deponent-imperatives, gerund, present-subjunctive.

What it checks, per skill:
  * app/data/grammar/sentences/<skill>.json is valid JSON with the contract shape,
    and its `skill` / `chapter` agree with skills.json
  * every printed word is a real inflected form of a word taught in a deck at or
    before the skill's chapter - the forms are GENERATED by pipeline/latin_forms.py
    from the glossary entry, so this tests morphology as well as membership - or a
    proper name of the book's cast, or the construction's own function word; every
    exception is listed with its justification
  * 5-8 printed words, or the sentence carries its own `note` saying why not, and
    the declared `words` count is the real one
  * `focus` occurs verbatim in `la`; `en`, `step`, `stage`, `kinds` present; every
    declared kind is one the skill declares; at least twelve sentences
  * the gloss has one entry per printed word, in order
  * every sentence id is unique, within the file and across all files checked
  * app/data/grammar/lessons/<skill>.json carries a `teach` block of 4-6 steps,
    numbered 1..n, each with a title, a `say`, and exactly one `check`
  * every sentence id a step names exists, and every step has a sentence of its own
  * every paradigm key used is in the paradigm_keys map in skills.json AND in the
    skill's own `paradigms` list
  * every paradigm cell key parses in the repo's cell-key convention, extended here
    to the gerund and imperative cells that paradigms.js already emits
  * the skill's `plain` string appears verbatim in the first teach step
  * core / more / sources of the lesson are still present and untouched in shape

Usage:  PYTHONIOENCODING=utf-8 python pipeline/check_teaching_ch22_27.py [skill ...]
"""

from __future__ import annotations

import json
import re
import sys
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GRAM = ROOT / "app" / "data" / "grammar"
sys.path.insert(0, str(ROOT / "pipeline"))

import latin_forms  # noqa: E402  (needs the path above)

DEFAULT_SKILLS = [
    "perfect-deponent",
    "future-participle",
    "future-infinitive",
    "pluperfect",
    "ablative-comparison",
    "deponent-imperatives",
    "gerund",
    "present-subjunctive",
]

#: Proper names of the book's cast and its places. The decks hold no proper
#: names at all (contract 7.2), so the contract admits them by rule, not as an
#: exception to be argued; each is spelled as Familia Romana prints it.
NAMES = {
    "iulius": "book cast: Iulius, the father",
    "iulii": "book cast: Iulius, the father",
    "iulio": "book cast: Iulius, the father",
    "iulium": "book cast: Iulius, the father",
    "aemilia": "book cast: Aemilia, the mother",
    "aemiliam": "book cast: Aemilia, the mother",
    "marcus": "book cast: Marcus, the elder son",
    "marci": "book cast: Marcus, the elder son",
    "marco": "book cast: Marcus, the elder son",
    "marcum": "book cast: Marcus, the elder son",
    "marce": "book cast: Marcus, the elder son (vocative)",
    "quintus": "book cast: Quintus, the younger son",
    "quinti": "book cast: Quintus, the younger son",
    "quinto": "book cast: Quintus, the younger son",
    "quintum": "book cast: Quintus, the younger son",
    "quinte": "book cast: Quintus, the younger son (vocative)",
    "iulia": "book cast: Iulia, the daughter",
    "iuliae": "book cast: Iulia, the daughter",
    "iuliam": "book cast: Iulia, the daughter",
    "syra": "book cast: Syra, the nurse",
    "syrae": "book cast: Syra, the nurse",
    "syram": "book cast: Syra, the nurse",
    "davus": "book cast: Davus, the slave",
    "davi": "book cast: Davus, the slave",
    "davo": "book cast: Davus, the slave",
    "davum": "book cast: Davus, the slave",
    "medus": "book cast: Medus, the runaway slave",
    "medi": "book cast: Medus, the runaway slave",
    "medo": "book cast: Medus, the runaway slave",
    "medum": "book cast: Medus, the runaway slave",
    "lydia": "book cast: Lydia, Medus's companion",
    "lydiae": "book cast: Lydia, Medus's companion",
    "lydiam": "book cast: Lydia, Medus's companion",
    "roma": "book place: Roma, the city",
    "romae": "book place: Roma, the city",
    "romam": "book place: Roma, the city",
    "graecia": "book place: Graecia, where Medus is sailing",
    "graeciam": "book place: Graecia, where Medus is sailing",
    "italia": "book place: Italia",
    "italiam": "book place: Italia",
    "tusculum": "book place: Tusculum",
    "tusculi": "book place: Tusculum",
    "tusculo": "book place: Tusculum",
}

#: Function words a construction owns (contract 1). Everything else must be in a deck.
FUNCTION_WORDS = {
    "ut": "the construction's own function word (ut = that, so that)",
    "ne": "the construction's own function word (ne = that not)",
    "cum": "the construction's own function word (cum = when, with)",
    "si": "the construction's own function word (si = if)",
}

#: Deck lemmas whose glossary headword is spelled otherwise (plural-only nouns).
LEMMA_ALIAS = {
    "liberi": "liber", "viscera": "viscus", "castra": "castrum",
    "arma": "armum", "cunae": "cuna", "complures": "complus", "fruges": "frux",
}

#: Printed spellings the decks file under their other form. Ørberg teaches
#: ā/ab and ē/ex as one preposition each; the deck prints only ab and ex.
WORD_ALIAS = {"a": "ab", "abs": "ab", "e": "ex"}

TENSES = {"pres", "impf", "fut", "perf", "plupf", "futperf"}
MOODS = {"ind", "subj"}
VOICES = {"act", "pass"}
PERSONS = {"1sg", "2sg", "3sg", "1pl", "2pl", "3pl"}
NUMBERS = {"sg", "pl"}
GENDERS = {"m", "f", "n"}
CASES = {"nom", "gen", "dat", "acc", "abl", "voc"}

WORD_RE = re.compile(r"[A-Za-zÀ-ɏḀ-ỿ]+")

_COMBINING = re.compile(r"[̀-ͯ]")


def plain(s: str) -> str:
    return _COMBINING.sub("", unicodedata.normalize("NFD", s or "")).lower()


def load(path: Path):
    with path.open(encoding="utf-8") as fh:
        return json.load(fh)


GLOSSARY = load(ROOT / "app" / "data" / "glossary.json")

# glossary headword -> its distinct entries (one per lemma/part of speech)
BY_HEAD: dict[str, dict] = {}
for _forms in GLOSSARY.values():
    for _e in _forms:
        _h = _e.get("h")
        if _h:
            BY_HEAD.setdefault(_h, {})[(_e.get("lemma"), _e.get("pos"))] = _e

_FORMS_CACHE: dict[str, dict[str, set[str]]] = {}


def generated_forms(head: str) -> dict[str, set[str]]:
    """Every regular inflected form of a headword: macron-stripped -> spellings."""
    if head in _FORMS_CACHE:
        return _FORMS_CACHE[head]
    out: dict[str, set[str]] = {}
    for entry in BY_HEAD.get(head, {}).values():
        try:
            for form, _parse in latin_forms.forms(entry):
                out.setdefault(plain(form), set()).add(form)
        except Exception:               # a table this generator cannot build
            continue
    _FORMS_CACHE[head] = out
    return out


_CUM_CACHE: dict[int, tuple[dict, dict]] = {}


def cumulative(chapter: int):
    """(headword -> (chapter, lemma), stripped form -> (chapter, lemma, spellings))."""
    if chapter in _CUM_CACHE:
        return _CUM_CACHE[chapter]
    heads: dict[str, tuple[int, str]] = {}
    forms: dict[str, tuple[int, str, set[str]]] = {}
    for n in range(1, chapter + 1):
        deck = GRAM / "vocab" / ("%02d.json" % n)
        if not deck.exists():
            continue
        for word in load(deck)["words"]:
            lemma = word["lemma"]
            for head in {plain(lemma), LEMMA_ALIAS.get(plain(lemma), plain(lemma))}:
                heads.setdefault(head, (n, lemma))
                for key, spellings in generated_forms(head).items():
                    if key in forms:
                        forms[key][2].update(spellings)
                    else:
                        forms[key] = (n, lemma, set(spellings))
    _CUM_CACHE[chapter] = (heads, forms)
    return heads, forms


def word_ok(word: str, cum) -> tuple[bool, str, bool]:
    """(inside the cumulative vocabulary?, why, does the spelling match the tables?)"""
    heads, forms = cum
    key = plain(word)
    if not key:
        return True, "punctuation", True
    if key in NAMES:
        return True, NAMES[key], True
    if key in forms:
        chapter, lemma, spellings = forms[key]
        ok = word in spellings or word[:1].lower() + word[1:] in spellings
        return True, "deck %02d (%s)" % (chapter, lemma), ok
    if key.endswith("que") and key[:-3] in forms:
        chapter, lemma, _ = forms[key[:-3]]
        return True, "deck %02d (%s) + -que" % (chapter, lemma), True
    if key in heads:                    # indeclinables the generator makes no forms for
        chapter, lemma = heads[key]
        return True, "deck %02d (%s)" % (chapter, lemma), True
    if WORD_ALIAS.get(key) in heads:    # ā for ab, ē for ex
        chapter, lemma = heads[WORD_ALIAS[key]]
        return True, "deck %02d (%s)" % (chapter, lemma), True
    for entry in GLOSSARY.get(key, []):
        head = entry.get("h")
        if head and head in heads:
            chapter, lemma = heads[head]
            return True, "deck %02d (%s)" % (chapter, lemma), True
    if key in FUNCTION_WORDS:
        return True, FUNCTION_WORDS[key], True
    return False, "NOT in the cumulative vocabulary", True


def cell_key_ok(key: str) -> bool:
    """The repo's cell-key convention, matching the key kinds paradigms.js emits.

    nominal    'case[.number][.gender]'        abl.sg, nom.pl.m
    finite     'tense.mood.voice.person+number'  plupf.ind.act.3sg
    infinitive 'inf.tense.voice'               inf.fut.act
    participle 'ptc.tense.voice'               ptc.perf.pass
    imperative 'imper.tense.voice.number'      imper.pres.pass.sg
    gerund     'gerund.case'                   gerund.acc
    supine     'supine.case'                   supine.acc
    """
    parts = key.split(".")
    if parts[0] in ("inf", "ptc"):
        return len(parts) == 3 and parts[1] in TENSES and parts[2] in VOICES
    if parts[0] == "imper":
        return (len(parts) == 4 and parts[1] in TENSES
                and parts[2] in VOICES and parts[3] in NUMBERS)
    if parts[0] in ("gerund", "supine"):
        return len(parts) == 2 and parts[1] in CASES
    if parts[0] in TENSES:
        return (len(parts) == 4 and parts[1] in MOODS
                and parts[2] in VOICES and parts[3] in PERSONS)
    if parts[0] in CASES:
        if len(parts) == 1:
            return True
        if len(parts) == 2:
            return parts[1] in NUMBERS
        if len(parts) == 3:
            return parts[1] in NUMBERS and parts[2] in GENDERS
    return False


def check_skill(skill: str, skills: dict, paradigm_keys: set,
                seen_ids: dict, exceptions: list, spellings: list):
    problems: list[str] = []
    meta = skills.get(skill)
    if meta is None:
        return ["%s is not in skills.json" % skill], {"skill": skill}

    chapter = meta["chapter"]
    cum = cumulative(chapter)

    spath = GRAM / "sentences" / (skill + ".json")
    lpath = GRAM / "lessons" / (skill + ".json")
    if not spath.exists():
        return ["no sentence file at %s" % spath], {"skill": skill}
    sfile, lfile = load(spath), load(lpath)

    if sfile.get("skill") != skill:
        problems.append("sentence file `skill` is %r" % sfile.get("skill"))
    if sfile.get("chapter") != chapter:
        problems.append("sentence file chapter %r, skills.json says %r"
                        % (sfile.get("chapter"), chapter))

    ids, longest, steps_used = set(), 0, set()
    for s in sfile.get("sentences", []):
        sid = s.get("id")
        if sid in seen_ids:
            problems.append("%s: id also used by %s" % (sid, seen_ids[sid]))
        seen_ids[sid] = skill
        ids.add(sid)
        steps_used.add(s.get("step"))

        words = WORD_RE.findall(s.get("la", ""))
        longest = max(longest, len(words))
        if s.get("words") != len(words):
            problems.append("%s: `words` says %r, printed words are %d"
                            % (sid, s.get("words"), len(words)))
        if not 5 <= len(words) <= 8 and not s.get("note"):
            problems.append("%s: %d words and no `note` giving the reason"
                            % (sid, len(words)))
        if s.get("focus") not in s.get("la", ""):
            problems.append("%s: focus %r is not verbatim in `la`" % (sid, s.get("focus")))
        if [g.get("w") for g in s.get("gloss", [])] != words:
            problems.append("%s: gloss does not match the printed words in order" % sid)
        for field in ("en", "step", "stage", "kinds"):
            if not s.get(field):
                problems.append("%s: missing %r" % (sid, field))
        for kind in s.get("kinds", []):
            if kind not in meta.get("kinds", []):
                problems.append("%s: kind %r is not one the skill declares" % (sid, kind))

        for word in words:
            ok, why, macrons = word_ok(word, cum)
            if not ok:
                problems.append("%s: %r - %s" % (sid, word, why))
            elif why.startswith(("book ", "the construction")):
                exceptions.append((plain(word), why))
            elif not macrons:
                spellings.append((sid, word, why))

    if len(sfile.get("sentences", [])) < 12:
        problems.append("only %d sentences; the contract asks for at least twelve"
                        % len(sfile.get("sentences", [])))

    for field in ("core", "more", "sources"):
        if not lfile.get(field):
            problems.append("lesson lost its %r block" % field)

    teach = lfile.get("teach")
    if not teach:
        problems.append("lesson has no `teach` block")
        return problems, {"skill": skill, "sentences": len(sfile.get("sentences", [])),
                          "steps": 0, "longest": longest}
    if not 4 <= len(teach) <= 6:
        problems.append("teach has %d steps; four to six are required" % len(teach))
    if meta.get("plain") and meta["plain"] not in (teach[0].get("say") or ""):
        problems.append("step 1 does not carry the skill's `plain` gloss verbatim")

    for i, step in enumerate(teach, 1):
        where = "teach step %d" % i
        if step.get("n") != i:
            problems.append("%s: `n` is %r" % (where, step.get("n")))
        for field in ("title", "say", "check"):
            if not step.get(field):
                problems.append("%s: missing %r" % (where, field))
        for label, block in (("show", step.get("show")), ("check", step.get("check"))):
            if not isinstance(block, dict):
                continue
            for field in ("id", "sentence"):
                ref = block.get(field)
                for one in ([ref] if isinstance(ref, str) else (ref or [])):
                    if one not in ids:
                        problems.append("%s %s: names sentence %r, which does not exist"
                                        % (where, label, one))
            if "key" in block:
                key = block["key"]
                if key not in paradigm_keys:
                    problems.append("%s %s: paradigm key %r is not in paradigm_keys"
                                    % (where, label, key))
                elif key not in meta.get("paradigms", []):
                    problems.append("%s %s: paradigm %r is not one of the skill's"
                                    % (where, label, key))
            for cell in (block.get("reveal") or []) + (block.get("cells") or []):
                if not cell_key_ok(cell):
                    problems.append("%s %s: cell key %r is malformed"
                                    % (where, label, cell))
        if step.get("n") not in steps_used:
            problems.append("%s has no sentence of its own" % where)

    return problems, {"skill": skill, "sentences": len(sfile.get("sentences", [])),
                      "steps": len(teach), "longest": longest}


def main(argv):
    raw = load(GRAM / "skills.json")
    skills = {s["id"]: s for s in raw["skills"]}
    paradigm_keys = set(raw["paradigm_keys"])

    targets = argv or DEFAULT_SKILLS
    seen_ids: dict[str, str] = {}
    exceptions: list = []
    spellings: list = []
    rows, all_problems = [], []

    print("check_teaching_ch22_27: %d skills\n" % len(targets))
    for skill in targets:
        problems, stats = check_skill(skill, skills, paradigm_keys,
                                      seen_ids, exceptions, spellings)
        rows.append(stats)
        print("  %-22s %2d sentences  %d teach steps  longest %d words%s"
              % (stats["skill"], stats.get("sentences", 0), stats.get("steps", 0),
                 stats.get("longest", 0), "   <-- PROBLEMS" if problems else ""))
        for p in problems:
            print("      ! %s" % p)
        all_problems += ["%s: %s" % (skill, p) for p in problems]

    counted: dict[str, tuple[str, int]] = {}
    for word, why in exceptions:
        why_, n = counted.get(word, (why, 0))
        counted[word] = (why_, n + 1)
    print("\nwords allowed as an exception to the decks (%d distinct), "
          "each with its justification:" % len(counted))
    for word in sorted(counted):
        why, n = counted[word]
        print("    %-14s x%-3d %s" % (word, n, why))

    if spellings:
        print("\nspellings the form generator prints without their macrons (%d), "
              "each checked against the deck's own lemma by hand:" % len(spellings))
        for sid, word, why in spellings:
            print("    %-10s %-14s %s" % (sid, word, why))

    print("\nsentences: %d   ids: %d unique" % (len(seen_ids), len(set(seen_ids))))
    if all_problems:
        print("problems: %d" % len(all_problems))
        return 1
    print("\nAll checks pass: JSON valid; every word a generated form of a word in "
          "the cumulative deck, or an allowed name or function word (listed above); "
          "word counts 5-8; declared counts right; focus verbatim in `la`; glosses "
          "complete and in order; every id unique; 4-6 teach steps each with one "
          "check and a sentence of its own; every referenced sentence exists; every "
          "paradigm key in paradigm_keys and in the skill's own list; every cell key "
          "well formed.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
