// Loads the skill map and the lessons (GRAMMAR-CONTRACT.md "skills.json",
// "Lesson JSON"). skills.json is the map; lessons/index.json (generated by
// pipeline/build_lessons_index.py) lists the lesson files that exist, so a
// skill without a lesson gets the "lesson coming" placeholder without a
// request that would 404. Everything is relative to app/, so it works under
// a sub-path too. The same loader serves ?fixture=1 (the real map and the
// real manifest); createLessonLoader() takes a fetcher for the tests.

import { roman } from '../sync.js';
export { roman };

const base = new URL('../../data/grammar/', import.meta.url);

async function fetchJson(name) {
  const res = await fetch(new URL(name, base));
  if (!res.ok) throw new Error(`${name}: ${res.status}`);
  return res.json();
}

/** { version, skills: Map id → skill, order: [ids], sample: bool, byChapter, byCourseWeek } */
export async function loadSkills() {
  return indexSkills(await fetchJson('skills.json'));
}

/**
 * The lessons manifest as a Set of skill ids: `{ "lessons": ["ablative-absolute", …] }`
 * (ids, or file names — ".json" is dropped). null for anything unusable, so
 * the loader falls back to asking for each lesson. Pure.
 */
export function manifestIds(raw) {
  const list = Array.isArray(raw) ? raw : Array.isArray(raw?.lessons) ? raw.lessons : null;
  if (!list) return null;
  return new Set(list.filter((x) => typeof x === 'string' && x).map((x) => x.replace(/\.json$/i, '')));
}

/**
 * A lesson loader over `fetchJson(name)` (relative to data/grammar/). The
 * manifest is read once; a skill it does not list is null at once (no
 * request); with no manifest every lesson is asked for and a miss is null.
 */
export function createLessonLoader({ fetchJson: fetcher = fetchJson } = {}) {
  const cache = new Map();
  let manifestP = null;
  const manifest = () => (manifestP ??= fetcher('lessons/index.json').then(manifestIds).catch(() => null));
  async function loadLesson(skillId) {
    if (cache.has(skillId)) return cache.get(skillId);
    const p = (async () => {
      const ids = await manifest();
      if (ids && !ids.has(skillId)) return null;
      let raw = null;
      try { raw = await fetcher(`lessons/${skillId}.json`); } catch { raw = null; }
      return raw ? normaliseLesson(raw) : null;
    })();
    cache.set(skillId, p);
    return p;
  }
  return { loadLesson, manifest, hasLesson: async (skillId) => { const ids = await manifest(); return ids ? ids.has(skillId) : (await loadLesson(skillId)) != null; } };
}

/** Pure: the loaded map indexed for the section. */
export function indexSkills(raw, sample = false) {
  const list = (raw?.skills ?? []).filter((s) => s && typeof s.id === 'string');
  const skills = new Map(list.map((s) => [s.id, {
    ...s,
    prereqs: Array.isArray(s.prereqs) ? s.prereqs : [],
    confusable_with: Array.isArray(s.confusable_with) ? s.confusable_with : [],
    kinds: Array.isArray(s.kinds) && s.kinds.length ? s.kinds : ['recognise', 'chart', 'parse', 'blank'],
    paradigms: Array.isArray(s.paradigms) ? s.paradigms : [],
    parse_filter: s.parse_filter && typeof s.parse_filter === 'object' ? s.parse_filter : null,   // null (metre): no wave-1 items
    course: String(s.course ?? ''),
    week: Number(s.week) || null,
    chapter: Number(s.chapter) || null,
  }]));
  const order = (Array.isArray(raw?.order) ? raw.order : []).filter((id) => skills.has(id));
  for (const id of skills.keys()) if (!order.includes(id)) order.push(id);
  return { version: raw?.version ?? 0, sample: sample || raw?.sample === true, skills, order, categories: [...new Set(list.map((s) => s.category).filter(Boolean))] };
}

/** Chapters in book order, each with its skills in map order. Pure. */
export function chapters(index) {
  const map = new Map();
  for (const id of index.order) {
    const s = index.skills.get(id);
    const ch = s.chapter ?? 0;
    if (!map.has(ch)) map.set(ch, []);
    map.get(ch).push(s);
  }
  return [...map.entries()].sort((a, b) => a[0] - b[0]).map(([chapter, skills]) => ({ chapter, skills }));
}

/** The skills a 103 week introduces (course "103", that week). Pure. */
export function weekSkills(index, weekN) {
  if (weekN == null) return [];
  return index.order.filter((id) => { const s = index.skills.get(id); return s.course === '103' && s.week === Number(weekN); });
}

const lessons = createLessonLoader();
/** The lesson for a skill, or null (the "lesson coming" placeholder) when the manifest does not list it. */
export const loadLesson = (skillId) => lessons.loadLesson(skillId);

/** Pure: a lesson with every block usable. */
export function normaliseLesson(l) {
  const blocks = (arr) => (Array.isArray(arr) ? arr.filter((b) => b && typeof b.type === 'string') : []);
  return { skill: l.skill, core: blocks(l.core), more: blocks(l.more), sources: Array.isArray(l.sources) ? l.sources : [], sample: l.sample === true };
}

/** Lesson prose: **bold** and *italic* → nodes (no HTML is ever parsed). Pure. */
export function inline(text) {
  const frag = document.createDocumentFragment();
  const re = /(\*\*[^*]+\*\*|\*[^*]+\*)/g;
  let last = 0;
  for (const m of String(text ?? '').matchAll(re)) {
    frag.append(text.slice(last, m.index));
    const s = m[0];
    if (s.startsWith('**')) { const b = document.createElement('b'); b.textContent = s.slice(2, -2); frag.append(b); }
    else { const i = document.createElement('i'); i.lang = 'la'; i.textContent = s.slice(1, -1); frag.append(i); }
    last = m.index + s.length;
  }
  frag.append(String(text ?? '').slice(last));
  return frag;
}
