// Loads the skill map and the lessons (GRAMMAR-CONTRACT.md "skills.json",
// "Lesson JSON"). skills.json is the map; lessons/index.json (generated by
// pipeline/build_lessons_index.py) lists the lesson files that exist, so a
// skill without a lesson gets the "lesson coming" placeholder without a
// request that would 404. Everything is relative to app/, so it works under
// a sub-path too. The same loader serves ?fixture=1 (the real map and the
// real manifest); createLessonLoader() takes a fetcher for the tests.

import { roman } from '../sync.js';
export { roman };

const base = new URL('../../data/grammar/', import.meta.url);

async function fetchJson(name) {
  const res = await fetch(new URL(name, base));
  if (!res.ok) throw new Error(`${name}: ${res.status}`);
  return res.json();
}

/** { version, skills: Map id → skill, order: [ids], sample: bool, byChapter, byCourseWeek } */
export async function loadSkills() {
  return indexSkills(await fetchJson('skills.json'));
}

/**
 * The lessons manifest as a Set of skill ids: `{ "lessons": ["ablative-absolute", …] }`
 * (ids, or file names — ".json" is dropped). null for anything unusable, so
 * the loader falls back to asking for each lesson. Pure.
 */
export function manifestIds(raw) {
  const list = Array.isArray(raw) ? raw : Array.isArray(raw?.lessons) ? raw.lessons : null;
  if (!list) return null;
  return new Set(list.filter((x) => typeof x === 'string' && x).map((x) => x.replace(/\.json$/i, '')));
}

/**
 * A lesson loader over `fetchJson(name)` (relative to data/grammar/). The
 * manifest is read once; a skill it does not list is null at once (no
 * request); with no manifest every lesson is asked for and a miss is null.
 */
export function createLessonLoader({ fetchJson: fetcher = fetchJson } = {}) {
  const cache = new Map();
  let manifestP = null;
  const manifest = () => (manifestP ??= fetcher('lessons/index.json').then(manifestIds).catch(() => null));
  async function loadLesson(skillId) {
    if (cache.has(skillId)) return cache.get(skillId);
    const p = (async () => {
      const ids = await manifest();
      if (ids && !ids.has(skillId)) return null;
      let raw = null;
      try { raw = await fetcher(`lessons/${skillId}.json`); }
      catch (e) {
        // A 404 is the placeholder for good; a network failure is not cached, so the next open asks again (m7).
        if (!/\b404\b/.test(String(e?.message ?? e))) cache.delete(skillId);
        raw = null;
      }
      return raw ? normaliseLesson(raw) : null;
    })();
    cache.set(skillId, p);
    return p;
  }
  /** The unit ids a lesson's examples block quotes (for the gold drill items); [] without a lesson. */
  const exampleUnits = async (skillId) => ((await loadLesson(skillId))?.core ?? []).filter((b) => b.type === 'examples').flatMap((b) => (Array.isArray(b.units) ? b.units.filter((u) => typeof u === 'string') : []));
  return { loadLesson, manifest, exampleUnits, hasLesson: async (skillId) => { const ids = await manifest(); return ids ? ids.has(skillId) : (await loadLesson(skillId)) != null; } };
}

/** Pure: the loaded map indexed for the section. */
export function indexSkills(raw, sample = false) {
  const list = (raw?.skills ?? []).filter((s) => s && typeof s.id === 'string');
  const skills = new Map(list.map((s) => [s.id, {
    ...s,
    prereqs: Array.isArray(s.prereqs) ? s.prereqs : [],
    confusable_with: Array.isArray(s.confusable_with) ? s.confusable_with : [],
    kinds: Array.isArray(s.kinds) && s.kinds.length ? s.kinds : ['recognise', 'chart', 'parse', 'blank'],
    paradigms: Array.isArray(s.paradigms) ? s.paradigms : [],
    parse_filter: s.parse_filter && typeof s.parse_filter === 'object' ? s.parse_filter : null,   // null (metre): no wave-1 items
    course: String(s.course ?? ''),
    week: Number(s.week) || null,
    chapter: Number(s.chapter) || null,
  }]));
  const order = (Array.isArray(raw?.order) ? raw.order : []).filter((id) => skills.has(id));
  for (const id of skills.keys()) if (!order.includes(id)) order.push(id);
  const paradigmKeys = raw?.paradigm_keys && typeof raw.paradigm_keys === 'object' ? raw.paradigm_keys : {};
  return { version: raw?.version ?? 0, sample: sample || raw?.sample === true, skills, order, categories: [...new Set(list.map((s) => s.category).filter(Boolean))], paradigmKeys };
}

/** Chapters in book order, each with its skills in map order. Pure. */
export function chapters(index) {
  const map = new Map();
  for (const id of index.order) {
    const s = index.skills.get(id);
    const ch = s.chapter ?? 0;
    if (!map.has(ch)) map.set(ch, []);
    map.get(ch).push(s);
  }
  return [...map.entries()].sort((a, b) => a[0] - b[0]).map(([chapter, skills]) => ({ chapter, skills }));
}

/** The skills a 103 week introduces (course "103", that week). Pure. */
export function weekSkills(index, weekN) {
  if (weekN == null) return [];
  return index.order.filter((id) => { const s = index.skills.get(id); return s.course === '103' && s.week === Number(weekN); });
}

const lessons = createLessonLoader();
/** The lesson for a skill, or null (the "lesson coming" placeholder) when the manifest does not list it. */
export const loadLesson = (skillId) => lessons.loadLesson(skillId);
export const lessonExampleUnits = (skillId) => lessons.exampleUnits(skillId);

/* ------------------------------- the written teaching sentences (§1) */
/**
 * `app/data/grammar/sentences/<skill>.json` — our own Latin, five to eight
 * words, inside the skill's cumulative chapter vocabulary, each sentence with
 * its `focus`, its English and a word-by-word `gloss`
 * (GRAMMAR-CONTRACT.md §1). **Learn draws from these and from nothing else**
 * (§8): a step's check names one of them by id, so the library never reaches
 * a teaching step.
 *
 * Pure: `normaliseSentences` cleans a fetched file; a sentence missing its
 * Latin or its id is dropped rather than half-shown.
 */
export function normaliseSentences(raw, skillId = null) {
  const list = Array.isArray(raw?.sentences) ? raw.sentences : Array.isArray(raw) ? raw : [];
  const out = [];
  for (const s of list) {
    const id = typeof s?.id === 'string' && s.id ? s.id : null;
    const la = typeof s?.la === 'string' && s.la.trim() ? s.la.trim() : null;
    if (!id || !la) continue;
    const gloss = Array.isArray(s.gloss) ? s.gloss.filter((g) => g && typeof g.w === 'string').map((g) => ({ w: g.w, m: String(g.m ?? '') })) : [];
    out.push({
      id, la, en: typeof s.en === 'string' ? s.en : '',
      focus: typeof s.focus === 'string' && s.focus ? s.focus : null,
      words: Number(s.words) || la.split(/\s+/).filter(Boolean).length,
      step: Number(s.step) || null, stage: Number(s.stage) || 1,
      kinds: Array.isArray(s.kinds) ? s.kinds.filter((k) => typeof k === 'string') : [],
      note: typeof s.note === 'string' ? s.note : '',
      gloss,
      // A generated sentence (§11a, §11b) says so and names its template; a written one carries neither.
      ...(s.generated === true ? { generated: true, template: typeof s.template === 'string' ? s.template : null } : {}),
    });
  }
  return { skill: raw?.skill ?? skillId, chapter: Number(raw?.chapter) || null, sentences: out };
}

/**
 * A loader for the two files Learn needs beside the lesson: the skill's
 * written sentences, and the paradigm catalogue (`paradigms.json`, §4a — every
 * table's stable id, its cells' ids and its three to five stock words). Both
 * are fetched once and shared; a miss is null and the step degrades to what it
 * can still show, never to a crash.
 */
export function createTeachDataLoader({ fetchJson: fetcher = fetchJson } = {}) {
  const cache = new Map();
  let catalogueP = null;
  const loadSentences = (skillId) => {
    if (!cache.has(skillId)) {
      cache.set(skillId, fetcher(`sentences/${skillId}.json`)
        .then((raw) => normaliseSentences(raw, skillId))
        .catch((e) => { if (!/(^|\D)404(\D|$)/.test(String(e?.message ?? e))) cache.delete(skillId); return null; }));
    }
    return cache.get(skillId);
  };
  const loadCatalogue = () => (catalogueP ??= fetcher('paradigms.json').then(indexCatalogue).catch(() => null));
  // The headword index (§4b) sits beside the glossary, one level up from data/grammar/: every lemma as
  // `[h, pos, key, i]`, which is how a written sentence's focus word is found when the glossary has no
  // key for the form the sentence prints (items.js `createTeachItems`). null when it cannot be loaded.
  let headwordsP = null;
  const loadHeadwords = () => (headwordsP ??= fetcher('../glossary-headwords.json').then((raw) => (Array.isArray(raw?.headwords) ? raw.headwords : null)).catch(() => null));
  // The reading tie-in (§10, §13): per skill and chapter, the highlight count `h` and the scanner count `s`
  // with the unit ids, no Latin. null when it cannot be loaded; the summary then simply has no line.
  let occurrencesP = null;
  const loadOccurrences = () => (occurrencesP ??= fetcher('occurrences.json').then((raw) => (raw && typeof raw === 'object' && raw.skills ? raw : null)).catch(() => null));
  // The generated banks (§11b): `generated/<skill>.json`, one per sentence skill with templates, pre-built by
  // pipeline/build_generated.py in the §11a shape. `generated/index.json` lists the skills that have one, so a
  // skill without a bank is null at once and no request 404s; with no manifest every bank is asked for.
  const banks = new Map();
  let bankManifestP = null;
  const bankManifest = () => (bankManifestP ??= fetcher('generated/index.json').then((raw) => manifestIds(Array.isArray(raw?.generated) ? raw.generated : raw)).catch(() => null));
  const loadGenerated = (skillId) => {
    if (!banks.has(skillId)) {
      banks.set(skillId, (async () => {
        const ids = await bankManifest();
        if (ids && !ids.has(skillId)) return null;
        try { return normaliseGenerated(await fetcher(`generated/${skillId}.json`), skillId); }
        catch (e) { if (!/(^|\D)404(\D|$)/.test(String(e?.message ?? e))) banks.delete(skillId); return null; }
      })());
    }
    return banks.get(skillId);
  };
  /** The skills that have a bank, from the manifest; null when there is no manifest (then ask per skill). */
  const generatedIds = () => bankManifest();
  return { loadSentences, loadCatalogue, loadHeadwords, loadOccurrences, loadGenerated, generatedIds };
}

/**
 * A generated bank cleaned for the app (§11b): the same sentence shape as the
 * written set, every sentence marked `generated: true` with its template, plus
 * the bank's `seeds` and `count`. Pure.
 */
export function normaliseGenerated(raw, skillId = null) {
  const base = normaliseSentences({ ...raw, sentences: (Array.isArray(raw?.sentences) ? raw.sentences : []).map((s) => ({ ...s, generated: true })) }, skillId);
  return { ...base, generated: true, seeds: Array.isArray(raw?.seeds) ? raw.seeds.map(Number).filter(Number.isFinite) : [], count: base.sentences.length };
}

/**
 * The reading tie-in's one line (GRAMMAR-CONTRACT.md §13 wording): **"the notes
 * mark N in this chapter"** when the count is the highlights' (`src` h — a
 * hand-picked subset, so a floor, never shown as a total), **"occurs about N
 * times in this chapter"** when only the scanner counted (`src` s). Ambiguous
 * scanner matches (`sx`) are never counted. `units` are the ids to light,
 * `{ week: 'r07', ids: ['46.1', …] }` per week. null when the file has no row
 * for the skill and chapter, or the count is nought. Pure.
 */
export function occurrenceLine(occurrences, skillId, chapter) {
  const row = occurrences?.skills?.[skillId]?.[String(chapter)];
  if (!row || typeof row !== 'object') return null;
  const src = row.src === 'h' ? 'h' : 's';
  const n = Number(src === 'h' ? row.h ?? row.n : row.s ?? row.n) || 0;
  if (n <= 0) return null;
  const units = Object.entries(row.ids ?? {}).map(([week, ids]) => ({ week, ids: String(ids ?? '').split(/\s+/).filter(Boolean) })).filter((u) => u.ids.length);
  const text = src === 'h' ? `The notes mark ${n} in this chapter.` : `It occurs about ${n} time${n === 1 ? '' : 's'} in this chapter.`;
  return { src, n, text, chapter: Number(chapter), units, unitIds: units.flatMap((u) => u.ids.map((id) => `${u.week}:${id}`)) };
}

/**
 * `paradigms.json` indexed for the app: `table(id)`, `tableOfKey(paradigmKey)`
 * — skills.json's 46 keys mapped onto the catalogue's 65 tables (§4a: the
 * branches paradigms.js really takes are finer than those keys in twenty
 * places) — and `cells(tableId)`, the set of cell ids that table names, which
 * is what a step's `show.reveal` and a chart check's `cells` are matched
 * against. Pure.
 */
export function indexCatalogue(raw) {
  const tables = new Map();
  for (const part of Array.isArray(raw?.parts) ? raw.parts : []) {
    for (const t of Array.isArray(part?.tables) ? part.tables : []) {
      if (t && typeof t.id === 'string') tables.set(t.id, { ...t, part: t.part ?? part.id ?? null });
    }
  }
  const keys = raw?.keys && typeof raw.keys === 'object' ? raw.keys : {};
  const cellsOf = new Map();
  for (const [id, t] of tables) cellsOf.set(id, new Set((t.groups ?? []).flatMap((g) => g.cells ?? [])));
  return {
    raw, tables, keys,
    table: (id) => tables.get(id) ?? null,
    /** The table a lesson's `paradigm key` names, or null. `adjcomp` names a **group** inside six adjective tables, so it resolves to no table of its own (§4a). */
    tableOfKey(key) {
      const named = keys[key];
      const first = Array.isArray(named?.tables) ? named.tables[0] : null;
      return (first && tables.get(first)) ?? tables.get(key) ?? null;
    },
    cells: (id) => cellsOf.get(id) ?? new Set(),
    /** The table's stock words (§4a), three to five per table, in the order the catalogue gives them. */
    stock: (id) => (tables.get(id)?.stock ?? []).map((w) => ({ ...w })),
  };
}

const teachData = createTeachDataLoader();
/** The skill's own written sentences (§1), or null when the file is not there. */
export const loadSentences = (skillId) => teachData.loadSentences(skillId);
/** The paradigm catalogue (§4a), indexed; null when it could not be loaded. */
export const loadParadigmCatalogue = () => teachData.loadCatalogue();
/** The headword index (§4b) as its rows, or null. */
export const loadHeadwords = () => teachData.loadHeadwords();
/** The reading tie-in's counts (`occurrences.json`, §13), or null. */
export const loadOccurrences = () => teachData.loadOccurrences();
/** The skill's generated bank (§11b), or null when it has none. */
export const loadGenerated = (skillId) => teachData.loadGenerated(skillId);
/** The ids of the skills with a generated bank (the manifest), or null without one. */
export const generatedSkillIds = () => teachData.generatedIds();

/** Pure: a lesson with every block usable, and its teach steps normalised. */
export function normaliseLesson(l) {
  const blocks = (arr) => (Array.isArray(arr) ? arr.filter((b) => b && typeof b.type === 'string') : []);
  return { skill: l.skill, teach: normaliseTeach(l.teach), core: blocks(l.core), more: blocks(l.more), sources: Array.isArray(l.sources) ? l.sources : [], sample: l.sample === true };
}

/* ------------------------------------------------ teach steps (§8) */
/**
 * The teach steps of a lesson (GRAMMAR-CONTRACT.md §2 and §8), cleaned and
 * put in `n` order. A step is **one idea**: its `say`, its `show`, an optional
 * `worked` example to complete, and its single `check` on that idea alone.
 * Anything unusable is dropped rather than half-rendered — a step with no
 * `say` and no `show` teaches nothing, so it is not a step.
 *
 *   { n, title, say, show: { kind: 'sentence', id } | { kind: 'paradigm', key, reveal: [cell id] },
 *     worked: { sentence, given: [feature], ask: [feature | 'why'] },
 *     check:  { kind, sentence } | { kind: 'chart', key, cells: [cell id], words: [headword] } }
 *
 * `words` on a chart check is §8's addition: the same cell asked on each word
 * in turn. Omitted, the table's own stock words answer for it (§4a), which is
 * why nothing here invents a lemma. Pure.
 */
export function normaliseTeach(raw) {
  const list = Array.isArray(raw) ? raw : [];
  const str = (v) => (typeof v === 'string' && v.trim() ? v.trim() : null);
  const ids = (v) => (Array.isArray(v) ? v.map(str).filter(Boolean) : []);
  const out = [];
  for (const s of list) {
    if (!s || typeof s !== 'object') continue;
    const show = normaliseShow(s.show);
    const check = normaliseCheck(s.check);
    const worked = normaliseWorked(s.worked);
    const notice = normaliseNotice(s.notice);
    const say = str(s.say);
    if (!say && !show && !check && !worked) continue;
    out.push({ n: Number(s.n) || out.length + 1, title: str(s.title) ?? '', say: say ?? '', notice, show, worked, check });
  }
  return out.sort((a, b) => a.n - b.n).map((s, i) => ({ ...s, n: i + 1 }));
}
function normaliseShow(v) {
  if (!v || typeof v !== 'object') return null;
  const kind = String(v.kind ?? '');
  if (kind === 'sentence') return typeof v.id === 'string' && v.id ? { kind: 'sentence', id: v.id } : null;
  if (kind === 'paradigm') {
    const key = typeof v.key === 'string' && v.key ? v.key : null;
    const reveal = Array.isArray(v.reveal) ? v.reveal.filter((c) => typeof c === 'string' && c) : [];
    // A paradigm shown with nothing revealed would be the whole table — the very thing §7.3 measured
    // (a median of 143 forms printed to teach six). No cells named, no table.
    return key && reveal.length ? { kind: 'paradigm', key, reveal } : null;
  }
  return null;
}
/**
 * A step's noticing opener (§10, amended): two of the skill's written sentences
 * side by side and one question, answered by tapping a word (`tap: 'focus'` —
 * the sentences' own focus words are the answer) or by picking an option
 * (`options`, with `answer` the right one). One screen, skippable in a tap,
 * never logged. Needs two sentence ids and a question; anything less is no
 * opener. Pure.
 */
function normaliseNotice(v) {
  if (!v || typeof v !== 'object') return null;
  const sentences = (Array.isArray(v.sentences) ? v.sentences : []).filter((id) => typeof id === 'string' && id).slice(0, 2);
  const ask = typeof v.ask === 'string' && v.ask.trim() ? v.ask.trim() : null;
  if (sentences.length < 2 || !ask) return null;
  const options = Array.isArray(v.options) ? v.options.filter((o) => typeof o === 'string' && o.trim()).map((o) => o.trim()) : [];
  const tap = v.tap === 'focus' || !options.length ? 'focus' : null;
  return { sentences, ask, tap, options, answer: typeof v.answer === 'string' ? v.answer : (Number.isInteger(v.answer) ? options[v.answer] ?? null : null) };
}
const CHECK_KINDS = new Set(['recognise', 'parse', 'blank', 'chart']);
function normaliseCheck(v) {
  if (!v || typeof v !== 'object') return null;
  const kind = String(v.kind ?? '');
  if (!CHECK_KINDS.has(kind)) return null;
  if (kind === 'chart') {
    const cells = Array.isArray(v.cells) ? v.cells.filter((c) => typeof c === 'string' && c) : [];
    if (!cells.length) return null;
    const words = Array.isArray(v.words) ? v.words.filter((w) => typeof w === 'string' && w) : null;
    return { kind, key: typeof v.key === 'string' && v.key ? v.key : null, cells, words: words && words.length ? words : null };
  }
  // `ask`: the step's own wording of the question, over the generator's stock line.
  return { kind, sentence: typeof v.sentence === 'string' && v.sentence ? v.sentence : null, ask: typeof v.ask === 'string' && v.ask.trim() ? v.ask.trim() : null };
}
const WORKED_FEATURES = new Set(['case', 'number', 'gender', 'tense', 'mood', 'voice', 'person', 'degree', 'construction', 'why']);
function normaliseWorked(v) {
  if (!v || typeof v !== 'object') return null;
  const sentence = typeof v.sentence === 'string' && v.sentence ? v.sentence : null;
  if (!sentence) return null;
  const feats = (x) => (Array.isArray(x) ? [...new Set(x.filter((f) => WORKED_FEATURES.has(f)))] : []);
  const given = feats(v.given).filter((f) => f !== 'why');
  const ask = feats(v.ask);
  return { sentence, given, ask };
}

/** Lesson prose: **bold** and *italic* → nodes (no HTML is ever parsed). Pure. */
export function inline(text) {
  const frag = document.createDocumentFragment();
  const re = /(\*\*[^*]+\*\*|\*[^*]+\*)/g;
  let last = 0;
  for (const m of String(text ?? '').matchAll(re)) {
    frag.append(text.slice(last, m.index));
    const s = m[0];
    if (s.startsWith('**')) { const b = document.createElement('b'); b.textContent = s.slice(2, -2); frag.append(b); }
    else { const i = document.createElement('i'); i.lang = 'la'; i.textContent = s.slice(1, -1); frag.append(i); }
    last = m.index + s.length;
  }
  frag.append(String(text ?? '').slice(last));
  return frag;
}

/* ------------------------------------------------ paradigm keys (G1-01) */
/** The lesson's paradigm keys → a glossary headword (the named tables) or the class a library word must belong to. */
export const KEY_CLASS = {
  decl1: { pos: 'N', cat: [1] }, decl2m: { pos: 'N', cat: [2, 1], gender: 'm' }, decl2n: { pos: 'N', cat: [2], gender: 'n' }, decl2r: { pos: 'N', cat: [2, 3] },
  decl3: { pos: 'N', cat: [3], gender: ['m', 'f', 'c'] }, decl3n: { pos: 'N', cat: [3], gender: 'n', catv: [1, 2] }, decl3i: { pos: 'N', cat: [3, 3], gender: ['m', 'f', 'c'] }, decl3in: { pos: 'N', cat: [3, 4], gender: 'n' },
  decl4: { pos: 'N', cat: [4, 1] }, decl4n: { pos: 'N', cat: [4, 2] }, decl5: { pos: 'N', cat: [5] },
  adj12: { pos: 'ADJ', cat: [1, 1] }, adj3: { pos: 'ADJ', cat: [3], catv: [2, 3] }, adj3cons: { pos: 'ADJ', cat: [3, 1] }, adjcomp: { pos: 'ADJ', comp: true },
  conj1: { pos: 'V', cat: [1, 1] }, conj2: { pos: 'V', cat: [2, 1] }, conj3: { pos: 'V', cat: [3, 1], io: false }, conj3io: { pos: 'V', cat: [3, 1], io: true }, conj4: { pos: 'V', cat: [3, 4] },
};
/** Model words for a class when the skill's own sentences offer none (looked up in the glossary; the reader's own words come first). */
export const KEY_MODELS = {
  decl1: ['puella', 'rosa', 'via'], decl2m: ['servus', 'hortus', 'dominus'], decl2n: ['oppidum', 'verbum', 'baculum'], decl2r: ['puer', 'liber', 'magister'],
  decl3: ['pastor', 'rex', 'mater', 'ovis'], decl3n: ['corpus', 'flumen', 'caput'], decl3i: ['navis', 'ovis', 'mons'], decl3in: ['mare', 'animal'], decl4: ['manus', 'exercitus'], decl4n: ['cornu'], decl5: ['dies', 'res'],
  adj12: ['bonus', 'magnus', 'pulcher'], adj3: ['fortis', 'brevis', 'omnis'], adj3cons: ['vetus', 'pauper'], adjcomp: ['fortior', 'maior', 'melior'],
  conj1: ['amo', 'voco', 'laudo'], conj2: ['video', 'habeo', 'moneo'], conj3: ['pono', 'scribo', 'duco'], conj3io: ['capio', 'facio', 'fugio'], conj4: ['audio', 'venio', 'dormio'],
};

/** True when a glossary entry belongs to the class a paradigm key names (KEY_CLASS). */
export function entryOfClass(entry, cls) {
  if (!entry || !cls || entry.pos !== cls.pos) return false;
  const [d, v] = entry.cat || [0, 0];
  if (cls.comp) return entry.kind === 'comp' || /-ior/.test(entry.lemma || '') || (entry.parses || []).some((p) => p.degree === 'comp');
  if (cls.cat && d !== cls.cat[0]) return false;
  if (cls.cat && cls.cat.length > 1 && v !== cls.cat[1]) return false;
  if (cls.catv && !cls.catv.includes(v)) return false;
  if (cls.gender && !(Array.isArray(cls.gender) ? cls.gender : [cls.gender]).includes(entry.gender)) return false;
  if (cls.io != null) { const io = /i$/.test(entry.roots?.[0] || ''); if (io !== cls.io) return false; }
  if (cls.pos === 'V' && (entry.kind === 'dep' || entry.kind === 'semidep' || entry.kind === 'impers')) return false;
  return true;
}

/**
 * The parses that light a lesson table: every cell the highlight names — both
 * numbers for a case, every person / number / voice for a finite tense
 * (paradigms.js matches finite cells strictly), both voices for a non-finite
 * form unless the highlight names one. Pure.
 */
export function highlightParses(filter) {
  const f = filter && typeof filter === 'object' && !Array.isArray(filter) ? filter : null;
  if (!f) return [];
  const list = (v) => (v == null ? [] : Array.isArray(v) ? v : [v]);
  const or = (v, d) => (list(v).length ? list(v) : d);
  const out = [];
  const moods = or(f.mood, f.tense ? ['ind', 'subj'] : f.case ? [undefined] : f.voice || f.person ? ['ind'] : [undefined]);
  for (const m of moods) {
    const finite = m === 'ind' || m === 'subj';
    const nonFinite = m === 'inf' || m === 'ptc' || m === 'imper';
    const tenses = or(f.tense, finite ? ['pres'] : m === 'gerund' || m === 'gerundive' || m === 'supine' ? [undefined] : nonFinite ? ['pres'] : [undefined]);
    const voices = or(f.voice, finite || nonFinite ? ['act', 'pass'] : [undefined]);
    const persons = or(f.person, finite ? [1, 2, 3] : [undefined]);
    const numbers = or(f.number, finite || m === 'imper' || f.case || m === 'ptc' || m === 'gerundive' ? ['sg', 'pl'] : [undefined]);
    const cases = or(f.case, m === 'gerund' || m === 'supine' ? ['gen', 'dat', 'acc', 'abl'] : [undefined]);
    for (const t of tenses) for (const v of voices) for (const pe of persons) for (const n of numbers) for (const c of cases) for (const g of or(f.gender, [undefined])) for (const d of or(f.degree, [undefined])) {
      const p = {};
      if (m) p.mood = m; if (t) p.tense = t; if (v) p.voice = v; if (pe != null) p.person = pe; if (n) p.number = n; if (c) p.case = c; if (g) p.gender = g; if (d) p.degree = d;
      if (Object.keys(p).length) out.push(p);
    }
  }
  return out;
}
