// Loads the skill map and the lessons (GRAMMAR-CONTRACT.md "skills.json",
// "Lesson JSON"). skills.json is the map; lessons/index.json (generated by
// pipeline/build_lessons_index.py) lists the lesson files that exist, so a
// skill without a lesson gets the "lesson coming" placeholder without a
// request that would 404. Everything is relative to app/, so it works under
// a sub-path too. The same loader serves ?fixture=1 (the real map and the
// real manifest); createLessonLoader() takes a fetcher for the tests.

import { roman } from '../sync.js';
export { roman };

const base = new URL('../../data/grammar/', import.meta.url);

async function fetchJson(name) {
  const res = await fetch(new URL(name, base));
  if (!res.ok) throw new Error(`${name}: ${res.status}`);
  return res.json();
}

/** { version, skills: Map id → skill, order: [ids], sample: bool, byChapter, byCourseWeek } */
export async function loadSkills() {
  return indexSkills(await fetchJson('skills.json'));
}

/**
 * The lessons manifest as a Set of skill ids: `{ "lessons": ["ablative-absolute", …] }`
 * (ids, or file names — ".json" is dropped). null for anything unusable, so
 * the loader falls back to asking for each lesson. Pure.
 */
export function manifestIds(raw) {
  const list = Array.isArray(raw) ? raw : Array.isArray(raw?.lessons) ? raw.lessons : null;
  if (!list) return null;
  return new Set(list.filter((x) => typeof x === 'string' && x).map((x) => x.replace(/\.json$/i, '')));
}

/**
 * A lesson loader over `fetchJson(name)` (relative to data/grammar/). The
 * manifest is read once; a skill it does not list is null at once (no
 * request); with no manifest every lesson is asked for and a miss is null.
 */
export function createLessonLoader({ fetchJson: fetcher = fetchJson } = {}) {
  const cache = new Map();
  let manifestP = null;
  const manifest = () => (manifestP ??= fetcher('lessons/index.json').then(manifestIds).catch(() => null));
  async function loadLesson(skillId) {
    if (cache.has(skillId)) return cache.get(skillId);
    const p = (async () => {
      const ids = await manifest();
      if (ids && !ids.has(skillId)) return null;
      let raw = null;
      try { raw = await fetcher(`lessons/${skillId}.json`); }
      catch (e) {
        // A 404 is the placeholder for good; a network failure is not cached, so the next open asks again (m7).
        if (!/\b404\b/.test(String(e?.message ?? e))) cache.delete(skillId);
        raw = null;
      }
      return raw ? normaliseLesson(raw) : null;
    })();
    cache.set(skillId, p);
    return p;
  }
  /** The unit ids a lesson's examples block quotes (for the gold drill items); [] without a lesson. */
  const exampleUnits = async (skillId) => ((await loadLesson(skillId))?.core ?? []).filter((b) => b.type === 'examples').flatMap((b) => (Array.isArray(b.units) ? b.units.filter((u) => typeof u === 'string') : []));
  return { loadLesson, manifest, exampleUnits, hasLesson: async (skillId) => { const ids = await manifest(); return ids ? ids.has(skillId) : (await loadLesson(skillId)) != null; } };
}

/** Pure: the loaded map indexed for the section. */
export function indexSkills(raw, sample = false) {
  const list = (raw?.skills ?? []).filter((s) => s && typeof s.id === 'string');
  const skills = new Map(list.map((s) => [s.id, {
    ...s,
    prereqs: Array.isArray(s.prereqs) ? s.prereqs : [],
    confusable_with: Array.isArray(s.confusable_with) ? s.confusable_with : [],
    kinds: Array.isArray(s.kinds) && s.kinds.length ? s.kinds : ['recognise', 'chart', 'parse', 'blank'],
    paradigms: Array.isArray(s.paradigms) ? s.paradigms : [],
    parse_filter: s.parse_filter && typeof s.parse_filter === 'object' ? s.parse_filter : null,   // null (metre): no wave-1 items
    course: String(s.course ?? ''),
    week: Number(s.week) || null,
    chapter: Number(s.chapter) || null,
  }]));
  const order = (Array.isArray(raw?.order) ? raw.order : []).filter((id) => skills.has(id));
  for (const id of skills.keys()) if (!order.includes(id)) order.push(id);
  const paradigmKeys = raw?.paradigm_keys && typeof raw.paradigm_keys === 'object' ? raw.paradigm_keys : {};
  return { version: raw?.version ?? 0, sample: sample || raw?.sample === true, skills, order, categories: [...new Set(list.map((s) => s.category).filter(Boolean))], paradigmKeys };
}

/** Chapters in book order, each with its skills in map order. Pure. */
export function chapters(index) {
  const map = new Map();
  for (const id of index.order) {
    const s = index.skills.get(id);
    const ch = s.chapter ?? 0;
    if (!map.has(ch)) map.set(ch, []);
    map.get(ch).push(s);
  }
  return [...map.entries()].sort((a, b) => a[0] - b[0]).map(([chapter, skills]) => ({ chapter, skills }));
}

/** The skills a 103 week introduces (course "103", that week). Pure. */
export function weekSkills(index, weekN) {
  if (weekN == null) return [];
  return index.order.filter((id) => { const s = index.skills.get(id); return s.course === '103' && s.week === Number(weekN); });
}

const lessons = createLessonLoader();
/** The lesson for a skill, or null (the "lesson coming" placeholder) when the manifest does not list it. */
export const loadLesson = (skillId) => lessons.loadLesson(skillId);
export const lessonExampleUnits = (skillId) => lessons.exampleUnits(skillId);

/** Pure: a lesson with every block usable. */
export function normaliseLesson(l) {
  const blocks = (arr) => (Array.isArray(arr) ? arr.filter((b) => b && typeof b.type === 'string') : []);
  return { skill: l.skill, core: blocks(l.core), more: blocks(l.more), sources: Array.isArray(l.sources) ? l.sources : [], sample: l.sample === true };
}

/** Lesson prose: **bold** and *italic* → nodes (no HTML is ever parsed). Pure. */
export function inline(text) {
  const frag = document.createDocumentFragment();
  const re = /(\*\*[^*]+\*\*|\*[^*]+\*)/g;
  let last = 0;
  for (const m of String(text ?? '').matchAll(re)) {
    frag.append(text.slice(last, m.index));
    const s = m[0];
    if (s.startsWith('**')) { const b = document.createElement('b'); b.textContent = s.slice(2, -2); frag.append(b); }
    else { const i = document.createElement('i'); i.lang = 'la'; i.textContent = s.slice(1, -1); frag.append(i); }
    last = m.index + s.length;
  }
  frag.append(String(text ?? '').slice(last));
  return frag;
}

/* ------------------------------------------------ paradigm keys (G1-01) */
/** The lesson's paradigm keys → a glossary headword (the named tables) or the class a library word must belong to. */
export const KEY_CLASS = {
  decl1: { pos: 'N', cat: [1] }, decl2m: { pos: 'N', cat: [2, 1], gender: 'm' }, decl2n: { pos: 'N', cat: [2], gender: 'n' }, decl2r: { pos: 'N', cat: [2, 3] },
  decl3: { pos: 'N', cat: [3], gender: ['m', 'f', 'c'] }, decl3n: { pos: 'N', cat: [3], gender: 'n', catv: [1, 2] }, decl3i: { pos: 'N', cat: [3, 3], gender: ['m', 'f', 'c'] }, decl3in: { pos: 'N', cat: [3, 4], gender: 'n' },
  decl4: { pos: 'N', cat: [4, 1] }, decl4n: { pos: 'N', cat: [4, 2] }, decl5: { pos: 'N', cat: [5] },
  adj12: { pos: 'ADJ', cat: [1, 1] }, adj3: { pos: 'ADJ', cat: [3], catv: [2, 3] }, adj3cons: { pos: 'ADJ', cat: [3, 1] }, adjcomp: { pos: 'ADJ', comp: true },
  conj1: { pos: 'V', cat: [1, 1] }, conj2: { pos: 'V', cat: [2, 1] }, conj3: { pos: 'V', cat: [3, 1], io: false }, conj3io: { pos: 'V', cat: [3, 1], io: true }, conj4: { pos: 'V', cat: [3, 4] },
};
/** Model words for a class when the skill's own sentences offer none (looked up in the glossary; the reader's own words come first). */
export const KEY_MODELS = {
  decl1: ['puella', 'rosa', 'via'], decl2m: ['servus', 'hortus', 'dominus'], decl2n: ['oppidum', 'verbum', 'baculum'], decl2r: ['puer', 'liber', 'magister'],
  decl3: ['pastor', 'rex', 'mater', 'ovis'], decl3n: ['corpus', 'flumen', 'caput'], decl3i: ['navis', 'ovis', 'mons'], decl3in: ['mare', 'animal'], decl4: ['manus', 'exercitus'], decl4n: ['cornu'], decl5: ['dies', 'res'],
  adj12: ['bonus', 'magnus', 'pulcher'], adj3: ['fortis', 'brevis', 'omnis'], adj3cons: ['vetus', 'pauper'], adjcomp: ['fortior', 'maior', 'melior'],
  conj1: ['amo', 'voco', 'laudo'], conj2: ['video', 'habeo', 'moneo'], conj3: ['pono', 'scribo', 'duco'], conj3io: ['capio', 'facio', 'fugio'], conj4: ['audio', 'venio', 'dormio'],
};

/** True when a glossary entry belongs to the class a paradigm key names (KEY_CLASS). */
export function entryOfClass(entry, cls) {
  if (!entry || !cls || entry.pos !== cls.pos) return false;
  const [d, v] = entry.cat || [0, 0];
  if (cls.comp) return entry.kind === 'comp' || /-ior/.test(entry.lemma || '') || (entry.parses || []).some((p) => p.degree === 'comp');
  if (cls.cat && d !== cls.cat[0]) return false;
  if (cls.cat && cls.cat.length > 1 && v !== cls.cat[1]) return false;
  if (cls.catv && !cls.catv.includes(v)) return false;
  if (cls.gender && !(Array.isArray(cls.gender) ? cls.gender : [cls.gender]).includes(entry.gender)) return false;
  if (cls.io != null) { const io = /i$/.test(entry.roots?.[0] || ''); if (io !== cls.io) return false; }
  if (cls.pos === 'V' && (entry.kind === 'dep' || entry.kind === 'semidep' || entry.kind === 'impers')) return false;
  return true;
}

/**
 * The parses that light a lesson table: every cell the highlight names — both
 * numbers for a case, every person / number / voice for a finite tense
 * (paradigms.js matches finite cells strictly), both voices for a non-finite
 * form unless the highlight names one. Pure.
 */
export function highlightParses(filter) {
  const f = filter && typeof filter === 'object' && !Array.isArray(filter) ? filter : null;
  if (!f) return [];
  const list = (v) => (v == null ? [] : Array.isArray(v) ? v : [v]);
  const or = (v, d) => (list(v).length ? list(v) : d);
  const out = [];
  const moods = or(f.mood, f.tense ? ['ind', 'subj'] : f.case ? [undefined] : f.voice || f.person ? ['ind'] : [undefined]);
  for (const m of moods) {
    const finite = m === 'ind' || m === 'subj';
    const nonFinite = m === 'inf' || m === 'ptc' || m === 'imper';
    const tenses = or(f.tense, finite ? ['pres'] : m === 'gerund' || m === 'gerundive' || m === 'supine' ? [undefined] : nonFinite ? ['pres'] : [undefined]);
    const voices = or(f.voice, finite || nonFinite ? ['act', 'pass'] : [undefined]);
    const persons = or(f.person, finite ? [1, 2, 3] : [undefined]);
    const numbers = or(f.number, finite || m === 'imper' || f.case || m === 'ptc' || m === 'gerundive' ? ['sg', 'pl'] : [undefined]);
    const cases = or(f.case, m === 'gerund' || m === 'supine' ? ['gen', 'dat', 'acc', 'abl'] : [undefined]);
    for (const t of tenses) for (const v of voices) for (const pe of persons) for (const n of numbers) for (const c of cases) for (const g of or(f.gender, [undefined])) for (const d of or(f.degree, [undefined])) {
      const p = {};
      if (m) p.mood = m; if (t) p.tense = t; if (v) p.voice = v; if (pe != null) p.person = pe; if (n) p.number = n; if (c) p.case = c; if (g) p.gender = g; if (d) p.degree = d;
      if (Object.keys(p).length) out.push(p);
    }
  }
  return out;
}
